
export const SYSTEM_EVENTS = {
  USER_DISCONNECTED: "USER_DISCONNECTED",
  USER_SUSPENDED: "USER_SUSPENDED",
  USER_UNSUSPENDED: "USER_UNSUSPENDED",
  USER_TERMINATED: "USER_TERMINATED",
  USER_RESTORED: "USER_RESTORED",
  USER_DELETED: "USER_DELETED",
    PAYMENT_APPROVED: "PAYMENT_APPROVED",
  PAYMENT_REJECTED: "PAYMENT_REJECTED",
  USER_SIGNUP: "USER_SIGNUP",
  ADMIN_NEW_USER: "ADMIN_NEW_USER",
  ADMIN_FIRST_LOGIN: "ADMIN_FIRST_LOGIN",
  NEW_PLAN_CREATED: "NEW_PLAN_CREATED",
};
