
export const SYSTEM_EVENTS = {
  USER_DISCONNECTED: "USER_DISCONNECTED",
  USER_SUSPENDED: "USER_SUSPENDED",
  USER_UNSUSPENDED: "USER_UNSUSPENDED",
  USER_TERMINATED: "USER_TERMINATED",
  USER_RESTORED: "USER_RESTORED",
  USER_DELETED: "USER_DELETED",
};
